import type { StyleSpecV1 } from '@/app/lib/spec/types';

/**
 * shadcn/ui Renderer
 * Generates a complete CSS variables theme (HSL-based) compatible with shadcn/ui.
 * shadcn/ui uses HSL CSS variables under :root and .dark selectors.
 */

function first(values: string[] | undefined, fallback: string): string {
  return values && values.length > 0 ? values[0] : fallback;
}

/**
 * Convert hex color to HSL string (h s% l%)
 */
function hexToHsl(hex: string): string {
  // Normalize: strip #, handle 3-digit shorthand, validate
  let clean = hex.replace('#', '');
  if (/^[0-9a-fA-F]{3}$/.test(clean)) {
    clean = clean[0] + clean[0] + clean[1] + clean[1] + clean[2] + clean[2];
  }
  if (!/^[0-9a-fA-F]{6}$/.test(clean)) return '0 0% 50%'; // fallback gray

  const r = parseInt(clean.substring(0, 2), 16) / 255;
  const g = parseInt(clean.substring(2, 4), 16) / 255;
  const b = parseInt(clean.substring(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }

  const hDeg = Math.round(h * 360);
  const sPct = Math.round(s * 100);
  const lPct = Math.round(l * 100);
  return `${hDeg} ${sPct}% ${lPct}%`;
}

function radiusValue(style: StyleSpecV1['radius']['style']): string {
  if (style === 'sharp') return '0';
  if (style === 'subtle') return '0.375rem';
  if (style === 'rounded') return '0.75rem';
  return '1.5rem'; // pill
}

/**
 * Generate shadcn/ui compatible CSS variables from StyleSpecV1.
 * Output: :root { --background: ...; --foreground: ...; ... }
 */
export function renderShadcnTheme(spec: StyleSpecV1): string {
  const bg = hexToHsl(first(spec.colors.background, '#ffffff'));
  const fg = hexToHsl(first(spec.colors.foreground, '#0f172a'));
  const fgMuted = hexToHsl(spec.colors.foreground[1] || '#64748b');
  const primary = hexToHsl(first(spec.colors.primary, '#2563eb'));
  const primaryFg = hexToHsl('#ffffff'); // text on primary
  const secondary = hexToHsl(first(spec.colors.secondary, '#7c3aed'));
  const secondaryFg = hexToHsl('#ffffff');
  const accent = hexToHsl(first(spec.colors.accent, '#f59e0b'));
  const accentFg = hexToHsl(first(spec.colors.foreground, '#0f172a'));
  const border = hexToHsl(first(spec.colors.border, '#e2e8f0'));
  const input = border; // shadcn uses border for input too
  const ring = primary;

  const card = bg;
  const cardFg = fg;
  const popover = bg;
  const popoverFg = fg;

  const destructive = hexToHsl(spec.colors.semantic?.danger || '#dc2626');
  const destructiveFg = hexToHsl('#ffffff');

  const muted = hexToHsl(spec.colors.foreground[1] || '#f1f5f9');
  const mutedFg = hexToHsl(spec.colors.foreground[1] || '#64748b');

  const radius = radiusValue(spec.radius.style);

  const headingFont = first(spec.typography.suggestedFonts, 'Inter');
  const bodyFont = spec.typography.suggestedFonts[1] || headingFont;

  return `/* ${spec.styleName} — shadcn/ui Theme */
/* Generated by Distill (distill.style) */

@layer base {
  :root {
    --background: ${bg};
    --foreground: ${fg};
    --card: ${card};
    --card-foreground: ${cardFg};
    --popover: ${popover};
    --popover-foreground: ${popoverFg};
    --primary: ${primary};
    --primary-foreground: ${primaryFg};
    --secondary: ${secondary};
    --secondary-foreground: ${secondaryFg};
    --muted: ${muted};
    --muted-foreground: ${mutedFg};
    --accent: ${accent};
    --accent-foreground: ${accentFg};
    --destructive: ${destructive};
    --destructive-foreground: ${destructiveFg};
    --border: ${border};
    --input: ${input};
    --ring: ${ring};
    --radius: ${radius};
    --font-heading: '${headingFont}', sans-serif;
    --font-body: '${bodyFont}', sans-serif;
    --font-weight-heading: ${spec.typography.headingWeight};
    --font-weight-body: ${spec.typography.bodyWeight};
    --letter-spacing: ${spec.typography.letterSpacing === 'tight' ? '-0.025em' : spec.typography.letterSpacing === 'wide' ? '0.025em' : '0em'};
    --shadow: ${spec.shadow.style === 'none' ? 'none' : '0 1px 3px rgba(15,23,42,0.08)'};
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground font-body;
    font-feature-settings: "rlig" 1, "calt" 1;
  }
  h1, h2, h3, h4, h5, h6 {
    @apply font-heading;
    font-weight: var(--font-weight-heading);
    letter-spacing: var(--letter-spacing);
  }
}`;
}

/**
 * Generate a components.json snippet for shadcn/ui CLI
 */
export function renderShadcnConfig(spec: StyleSpecV1): string {
  const headingFont = first(spec.typography.suggestedFonts, 'Inter');
  const bodyFont = spec.typography.suggestedFonts[1] || headingFont;

  return `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  },
  "fonts": {
    "heading": "${headingFont}",
    "body": "${bodyFont}"
  }
}`;
}
